dist: trusty
env: "GRADLE_OPTS=\"-Xms1g -Xmx3g\""
jdk: 
  - oraclejdk8
language: java
notifications: 
  email: true
script: 
  - "./gradlew build"
  - "./gradlew curseforge --stacktrace"
sudo: required